
[font]
size = 16.0

[scrolling]
history = 100000

[selection]
save_to_clipboard = true

[general]
import = [
	"~/.config/alacritty/themes/themes/everforest_light.toml",
	"~/.config/alacritty/osx.toml",
	"~/.config/alacritty/arch.toml",
]
