import = [
    "~/.config/alacritty/themes/themes/everforest_light.toml"
]

[font]
size=13.0

[scrolling]
history = 100000

[selection]
save_to_clipboard= true

[font.normal]
# For Arch linux, install ttf-inconsolata-nerd
family = "Inconsolata NerdFont Mono"

# For OSX, install font-inconsolata-nerd-font from brew
# brew install --cask font-inconsolata-nerd-font
#family = "Inconsolata Nerd Font Mono"

