[tool.isort]
profile = "pycharm"
line_length = 120

[tool.black]
line-length = 120

[tool.basedpyright]
typeCheckingMode = "basic"

[tool.ruff]
line-length = 120

[tool.ruff.lint]
ignore = ['COM812']
